version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: identity-postgres
    environment:
      POSTGRES_DB: identity_db
      POSTGRES_USER: identity_user
      POSTGRES_PASSWORD: identity_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - identity-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U identity_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  identity-service:
    build: .
    container_name: identity-service
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://identity_user:identity_pass@postgres:5432/identity_db
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRATION: 1h
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - identity-network
    volumes:
      - ./src:/app/src
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:

networks:
  identity-network:
    driver: bridge
